theme: jekyll-theme-cayman
title: My Research
show_downloads: true
color:
  header: "#FFFFFF"
  gradient_left: "#34e89e"
  gradient_right: "#0f3443"
buttons:
      zip_url: https://Ziqian-xia.github.io
      zip_title: Back to Homepage
      zip_hide: false
      tar_url: http://example.com/
      tar_title: Latest Talk
      tar_hide: true
      github_hide: true # hides "View on Github"
plugins:
  - jekyll-relative-links
relative_links:
  enabled: false
  collections: false
