theme: jekyll-theme-cayman
remote_theme: tuur29/pages-themes-cayman
title: My Research
show_downloads: false
color:
  header: "#FFFFFF"
  gradient_left: "#007991"
  gradient_right: "#78ffd6"
buttons:
      zip_url: https://github.com/Ziqian-xia/Ziqian-xia.github.io/blob/gh-pages/CV-Ziqian.pdf
      zip_title: CV
      zip_hide: true
      tar_url: http://example.com/
      tar_title: Latest Talk
      tar_hide: true
      github_hide: true # hides "View on Github"
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
